In [34]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
os.chdir("C:\\Users\\Ganesh\\RandPython")
from sklearn.datasets import make_classification, make_blobs

from sklearn.metrics import confusion_matrix
from matplotlib.colors import ListedColormap
from sklearn.datasets import load_breast_cancer


In [80]:
# Setting return-X_y=True returns the features and the target variable
(X_cancer, y_cancer) = load_breast_cancer(return_X_y = True)

In [19]:
from sklearn.linear_model import LogisticRegression
from adspy_shared_utilities import (
plot_class_regions_for_classifier_subplot)
X_train, X_test, y_train, y_test = train_test_split(X_cancer, y_cancer,
                                                   random_state = 0)

In [20]:
clf = LogisticRegression().fit(X_train, y_train)

(143L, 30L)

In [31]:
fig, subaxes = plt.subplots(1, 1, figsize=(7, 5))
clf = LogisticRegression().fit(X_train, y_train)


print('Accuracy of Logistic regression classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print('Accuracy of Logistic regression classifier on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

Accuracy of Logistic regression classifier on training set: 0.96
Accuracy of Logistic regression classifier on test set: 0.96


In [35]:
y_predicted=clf.predict(X_test)
confusion = confusion_matrix(y_test, y_predicted)

In [36]:
confusion

array([[52,  1],
       [ 5, 85]])

In [37]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
# Accuracy = TP + TN / (TP + TN + FP + FN) (All positives/(All))
# Precision = TP / (TP + FP) Ratio of True of positives among all positives
# Recall = TP / (TP + FN)  Also known as sensitivity, or True Positive Rate  (True positive)/()
# F1 = 2 * Precision * Recall / (Precision + Recall) 
print('Accuracy: {:.2f}'.format(accuracy_score(y_test, y_predicted)))
print('Precision: {:.2f}'.format(precision_score(y_test, y_predicted)))
print('Recall: {:.2f}'.format(recall_score(y_test, y_predicted)))
print('F1: {:.2f}'.format(f1_score(y_test, y_predicted)))

Accuracy: 0.96
Precision: 0.99
Recall: 0.94
F1: 0.97


In [83]:
y_cancer=y_cancer.reshape(569L,1L)
cancer=np.append(X_cancer,y_cancer,axis=1)
np.savetxt("cancer.csv", cancer, delimiter=",")

In [84]:
cancer.shape

(569L, 31L)

In [86]:

X_cancer

array([[  1.79900000e+01,   1.03800000e+01,   1.22800000e+02, ...,
          2.65400000e-01,   4.60100000e-01,   1.18900000e-01],
       [  2.05700000e+01,   1.77700000e+01,   1.32900000e+02, ...,
          1.86000000e-01,   2.75000000e-01,   8.90200000e-02],
       [  1.96900000e+01,   2.12500000e+01,   1.30000000e+02, ...,
          2.43000000e-01,   3.61300000e-01,   8.75800000e-02],
       ..., 
       [  1.66000000e+01,   2.80800000e+01,   1.08300000e+02, ...,
          1.41800000e-01,   2.21800000e-01,   7.82000000e-02],
       [  2.06000000e+01,   2.93300000e+01,   1.40100000e+02, ...,
          2.65000000e-01,   4.08700000e-01,   1.24000000e-01],
       [  7.76000000e+00,   2.45400000e+01,   4.79200000e+01, ...,
          0.00000000e+00,   2.87100000e-01,   7.03900000e-02]])

In [73]:
a=np.arange(12).reshape(3,4)
a
print(a.shape)
b=np.arange(3).reshape(3,1)
print(b.shape)
np.append(a,b,axis=1)


(3L, 4L)
(3L, 1L)


array([[ 0,  1,  2,  3,  0],
       [ 4,  5,  6,  7,  1],
       [ 8,  9, 10, 11,  2]])

In [79]:
X_cancer.shape
y_cancer=y_cancer.reshape(569,1)
y_cancer.shape

(569L, 1L)

In [82]:
np.append(X_cancer,y_cancer,axis=1)

array([[  1.79900000e+01,   1.03800000e+01,   1.22800000e+02, ...,
          4.60100000e-01,   1.18900000e-01,   0.00000000e+00],
       [  2.05700000e+01,   1.77700000e+01,   1.32900000e+02, ...,
          2.75000000e-01,   8.90200000e-02,   0.00000000e+00],
       [  1.96900000e+01,   2.12500000e+01,   1.30000000e+02, ...,
          3.61300000e-01,   8.75800000e-02,   0.00000000e+00],
       ..., 
       [  1.66000000e+01,   2.80800000e+01,   1.08300000e+02, ...,
          2.21800000e-01,   7.82000000e-02,   0.00000000e+00],
       [  2.06000000e+01,   2.93300000e+01,   1.40100000e+02, ...,
          4.08700000e-01,   1.24000000e-01,   0.00000000e+00],
       [  7.76000000e+00,   2.45400000e+01,   4.79200000e+01, ...,
          2.87100000e-01,   7.03900000e-02,   1.00000000e+00]])